# Generated by Django 5.2.15 on 2026-07-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beyblade',
            name='spin_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beyblade', to='api.spintrack'),
        ),
    ]
